name: ${pluginName}
version: ${version}
main: com.willfp.ecomenus.EcoMenusPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco

commands:
  ecomenus:
    description: Base Command
    permission: ecomenus.command.ecomenus

permissions:
  ecomenus.*:
    description: All ecomenus permissions
    default: op
    children:
      ecomenus.command.*: true
  ecomenus.command.*:
    description: All commands
    default: op
    children:
      ecomenus.command.reload: true
      ecomenus.command.ecomenus: true

  ecomenus.command.reload:
    description: Allows reloading the config
    default: op
  ecomenus.command.ecomenus:
    description: Allows the use of /ecomenus.
    default: true
